In [1]:

import polars as pl
from sklearn.metrics import accuracy_score

from autotsc.models import AutoTSCModel
from autotsc.utils import load_dataset

2025-11-17 15:23:21.426011: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

In [2]:
import ray

ray.shutdown()
ray.init(num_cpus=24)

2025-11-17 15:23:26,866	INFO worker.py:2012 -- Started a local Ray instance.
/home/gasper_p/workspace/repos/AutoTSC/.venv/lib/python3.12/site-packages/ray/_private/worker.py:2051: FutureWarning: Tip: In future versions of Ray, Ray will no longer override accelerator visible devices env var if num_gpus=0 or num_gpus=None (default). To enable this behavior and turn off this error message, set RAY_ACCEL_ENV_VAR_OVERRIDE_ON_ZERO=0
  warnings.warn(

RayContext(dashboard_url='', python_version='3.12.0', ray_version='2.51.1', ray_commit='eeb38c79c1af96df29cbacab7b8a823d489237f3')

In [3]:
X_train, y_train, X_test, y_test = load_dataset("Computers")
# X_train, y_train, X_test, y_test = load_dataset("ArrowHead")
X_train, y_train, X_test, y_test = load_dataset("CricketZ")
#X_train, y_train, X_test, y_test = load_dataset("FordB")

#X_train, y_train, X_test, y_test = load_dataset("MelbournePedestrian")
# X_train, y_train, X_test, y_test = load_dataset("TwoPatterns")



model = AutoTSCModel(n_jobs=-1, model_types="rocket-catch22", verbose=True, use_stacking=True, use_only_best_model=False)

In [4]:
model.fit(X_train, y_train)

|------------------------|
| Number of samples: 390 |
| Number of channels: 1  |
| Length of series: 300  |
| Number of classes: 12  |
| CPUs: 24/24            |
| GPUs: 2/2              |
|------------------------|

(train_fold pid=817355) 2025-11-17 15:23:34.707583: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(train_fold pid=817355) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

Model 0 fitted, accuracy: 0.8256, time: 0.56s
Model 1 fitted, accuracy: 0.5974, time: 0.61s

(pid=gcs_server) [2025-11-17 15:23:54,339 E 817105 817105] (gcs_server) gcs_server.cc:302: Failed to establish connection to the event+metrics exporter agent. Events and metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(train_fold pid=817364) 2025-11-17 15:23:34.707585: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations. [repeated 5x across cluster] (Ray deduplicates logs by default. Set RAY_DEDUP_LOGS=0 to disable log deduplication, or see https://docs.ray.io/en/master/ray-observability/user-guides/configure-logging.html#log-deduplication for more options.)
(train_fold pid=817364) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags. [repeated 5x across cluster]
(raylet) [2025-11-17 15:23:57,424 E 817258 817258] (raylet) main.cc:975: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(train_fold pid=817361) [2025-11-17 15:23:59,803 E 817361 817402] core_worker_process.cc:825: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
[2025-11-17 15:24:00,791 E 817032 817341] core_worker_process.cc:825: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14

AutoTSCModel(model_types='rocket-catch22', verbose=True)

In [5]:
model.model_predictions

shape: (390, 24)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ model_0__ ┆ model_0__ ┆ model_0__ ┆ model_0__ ┆ … ┆ model_1__ ┆ model_1__ ┆ model_1__ ┆ model_1_ │
│ class_1   ┆ class_10  ┆ class_11  ┆ class_12  ┆   ┆ class_6   ┆ class_7   ┆ class_8   ┆ _class_9 │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.079906  ┆ 0.111384  ┆ 0.075556  ┆ 0.101135  ┆ … ┆ 0.4       ┆ 0.025     ┆ 0.105     ┆ 0.06     │
│ 0.074623  ┆ 0.07547   ┆ 0.073327  ┆ 0.055895  ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ 0.075084  ┆ 0.14065   ┆ 0.106507  ┆ 0.070185  ┆ … ┆ 0.025     ┆ 0.0       ┆ 0.125     ┆ 0.025    │
│ 0.154216  ┆ 0.083602  ┆ 0.061822  ┆ 0.061104  ┆ … ┆ 0.07      ┆ 0.155     ┆ 0.03      ┆ 0.045    │
│ 0.064218  ┆ 0.059871  ┆ 0.08083   ┆ 0.080744  ┆ … ┆ 0.165     ┆ 0.0       ┆ 0.205     ┆ 0.095    │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 0.052239  ┆ 0.060282  ┆ 0.085295  ┆ 0.077592  ┆ … ┆ 0.085     ┆ 0.49      ┆ 0.0       ┆ 0.11     │
│ 0.064779  ┆ 0.076204  ┆ 0.070173  ┆ 0.060426  ┆ … ┆ 0.04      ┆ 0.72      ┆ 0.025     ┆ 0.035    │
│ 0.06899   ┆ 0.172018  ┆ 0.07838   ┆ 0.078882  ┆ … ┆ 0.04      ┆ 0.0       ┆ 0.055     ┆ 0.06     │
│ 0.061713  ┆ 0.099805  ┆ 0.090982  ┆ 0.145311  ┆ … ┆ 0.13      ┆ 0.205     ┆ 0.04      ┆ 0.045    │
│ 0.08019   ┆ 0.093827  ┆ 0.144789  ┆ 0.064671  ┆ … ┆ 0.08      ┆ 0.005     ┆ 0.225     ┆ 0.185    │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [13]:
model.folds_

shape: (12, 3)
┌──────┬───────────────┬─────────────────┐
│ fold ┆ train_idx     ┆ test_idx        │
│ ---  ┆ ---           ┆ ---             │
│ i64  ┆ list[i64]     ┆ list[i64]       │
╞══════╪═══════════════╪═════════════════╡
│ 0    ┆ [0, 1, … 389] ┆ [12, 16, … 373] │
│ 1    ┆ [0, 1, … 389] ┆ [19, 22, … 377] │
│ 2    ┆ [0, 1, … 389] ┆ [21, 27, … 375] │
│ 3    ┆ [0, 1, … 389] ┆ [28, 33, … 372] │
│ 4    ┆ [0, 2, … 388] ┆ [1, 7, … 389]   │
│ …    ┆ …             ┆ …               │
│ 7    ┆ [1, 2, … 389] ┆ [0, 3, … 381]   │
│ 8    ┆ [0, 1, … 389] ┆ [5, 14, … 387]  │
│ 9    ┆ [0, 1, … 389] ┆ [18, 30, … 380] │
│ 10   ┆ [0, 1, … 389] ┆ [11, 20, … 388] │
│ 11   ┆ [0, 1, … 389] ┆ [9, 45, … 364]  │
└──────┴───────────────┴─────────────────┘

In [ ]:
from sklearn import clone
from sklearn.ensemble import RandomForestClassifier
from autotsc.models import RidgeClassifierCVWithProba
import numpy as np

class Ensemble:
    def __init__(self, folds, estimator):
        self.folds = folds
        self.estimator = estimator
        self.model_ = None
        
    def fit_predict(self, X, y):
        predictions = []
        for fold in self.folds.rows(named=True):
            X_train = X[fold['train_idx'], :]
            y_train = y[fold['train_idx']]
            X_test = X[fold['test_idx'], :]
            self.model_ = clone(self.estimator)
            self.model_.fit(X_train, y_train)
            y_pred = self.model_.predict(X_test)
            #acc = accuracy_score(y[fold['test_idx']], y_pred)
            y_pred_zip = zip(fold['test_idx'], y_pred.tolist())
            predictions.extend(y_pred_zip)
        predictions = sorted(predictions)
        fold_predictions = [p[1] for p in predictions]
        return fold_predictions
    
    def predict(self, X):
        return self.model_.predict(X)


    

em = Ensemble(model.folds_, RidgeClassifierCVWithProba(alphas=np.logspace(-4, 4, 50)))
pred = em.fit_predict(model.model_predictions, model.y_)
print(accuracy_score(model.y_, pred))

em = Ensemble(model.folds_, RandomForestClassifier(n_jobs=-1))
pred = em.fit_predict(model.model_predictions, model.y_)
print(accuracy_score(model.y_, pred))

0.7923076923076923
0.8102564102564103

In [6]:
werwer=wfwerf

NameError: name 'wfwerf' is not defined

In [21]:
summary = model.summary()
summary

shape: (6, 8)
┌───────────┬────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┐
│ model_id  ┆ classifier ┆ fold_predi ┆ fold_proba ┆ true_labe ┆ validatio ┆ training_ ┆ stacking_ │
│ ---       ┆ ---        ┆ ctions     ┆ bilities   ┆ ls        ┆ n_accurac ┆ time_seco ┆ level     │
│ str       ┆ str        ┆ ---        ┆ ---        ┆ ---       ┆ y         ┆ nds       ┆ ---       │
│           ┆            ┆ list[str]  ┆ list[list[ ┆ list[str] ┆ ---       ┆ ---       ┆ i64       │
│           ┆            ┆            ┆ f64]]      ┆           ┆ f64       ┆ f64       ┆           │
╞═══════════╪════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ pca-ridge ┆ Pipeline(s ┆ ["6", "5", ┆ null       ┆ ["6",     ┆ 0.571795  ┆ null      ┆ 1         │
│           ┆ teps=[('pc ┆ … "11"]    ┆            ┆ "5", …    ┆           ┆           ┆           │
│           ┆ a',PCA(n_c ┆            ┆            ┆ "11"]     ┆           ┆           ┆           │
│           ┆ …          ┆            ┆            ┆           ┆           ┆           ┆           │
│ 1         ┆ Catch22Cla ┆ ["6", "5", ┆ [[0.04,    ┆ ["6",     ┆ 0.597436  ┆ 0.60899   ┆ 0         │
│           ┆ ssifier(n_ ┆ … "8"]     ┆ 0.05, …    ┆ "5", …    ┆           ┆           ┆           │
│           ┆ jobs=4,ran ┆            ┆ 0.06],     ┆ "11"]     ┆           ┆           ┆           │
│           ┆ …          ┆            ┆ [0.0, 0…   ┆           ┆           ┆           ┆           │
│ ridge     ┆ RidgeClass ┆ ["6", "5", ┆ null       ┆ ["6",     ┆ 0.746154  ┆ null      ┆ 1         │
│           ┆ ifierCV()  ┆ … "11"]    ┆            ┆ "5", …    ┆           ┆           ┆           │
│           ┆            ┆            ┆            ┆ "11"]     ┆           ┆           ┆           │
│ hgb       ┆ HistGradie ┆ ["12",     ┆ null       ┆ ["6",     ┆ 0.8       ┆ null      ┆ 1         │
│           ┆ ntBoosting ┆ "5", …     ┆            ┆ "5", …    ┆           ┆           ┆           │
│           ┆ Classifier ┆ "11"]      ┆            ┆ "11"]     ┆           ┆           ┆           │
│           ┆ …          ┆            ┆            ┆           ┆           ┆           ┆           │
│ rf        ┆ RandomFore ┆ ["12",     ┆ null       ┆ ["6",     ┆ 0.802564  ┆ null      ┆ 1         │
│           ┆ stClassifi ┆ "5", …     ┆            ┆ "5", …    ┆           ┆           ┆           │
│           ┆ er(n_estim ┆ "11"]      ┆            ┆ "11"]     ┆           ┆           ┆           │
│           ┆ …          ┆            ┆            ┆           ┆           ┆           ┆           │
│ 0         ┆ RocketClas ┆ ["10",     ┆ [[0.079906 ┆ ["6",     ┆ 0.825641  ┆ 0.560877  ┆ 0         │
│           ┆ sifier(est ┆ "5", …     ┆ ,          ┆ "5", …    ┆           ┆           ┆           │
│           ┆ imator=Rid ┆ "11"]      ┆ 0.111384,  ┆ "11"]     ┆           ┆           ┆           │
│           ┆ …          ┆            ┆ … 0.0675…  ┆           ┆           ┆           ┆           │
└───────────┴────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┘

In [ ]:
p = model.predict_proba_per_model(X_test)

In [ ]:
preds = model.predict_per_model(X_test)

In [ ]:
sdf = []

for x, y in preds.items():
    acc = accuracy_score(y_test, y)
    sdf.append({"model_id": x, "test_accuracy": acc})
sdf = pl.DataFrame(sdf)
sdf

In [ ]:
summary = summary.join(sdf, on="model_id")
summary.sort("test_accuracy")

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

df = summary.to_pandas()

ax = sns.scatterplot(data=df, x="validation_accuracy", y="test_accuracy", hue="stacking_level")

for i, row in df.iterrows():
    ax.text(
        row["validation_accuracy"],
        row["test_accuracy"],
        str(row["model_id"]),
        fontsize=9,
        ha="right",
        va="bottom",
    )
plt.grid()
plt.show()

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

df = summary.to_pandas()

ax = sns.scatterplot(
    data=df, x="validation_accuracy", y="training_time_seconds", hue="stacking_level"
)

for i, row in df.iterrows():
    ax.text(
        row["validation_accuracy"],
        row["training_time_seconds"],
        str(row["model_id"]),
        fontsize=9,
        ha="right",
        va="bottom",
    )
plt.grid()
plt.show()

In [ ]:
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.4f}")

In [ ]:
from aeon.classification.convolution_based import (
    MultiRocketClassifier,
)

clf2 = MultiRocketClassifier(n_jobs=-1)
clf2.fit(X_train, y_train)
y_pred2 = clf2.predict(X_test)
accuracy2 = accuracy_score(y_test, y_pred2)
print(f"MultiRocket Accuracy: {accuracy2:.4f}")

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

sns.scatterplot(
    data=model.summary().to_pandas(),
    x="validation_accuracy",
    y="training_time_seconds",
    hue="model_id",
)
plt.grid()
plt.yscale("log")