In [1]:
import numpy as np
from aeon.classification.interval_based import RSTSF
from sklearn.metrics import accuracy_score
from tscglue.models import LokyStackerV7, LokyStackerV7SoftFilterRidge, TSCGlue, LokyStackerV8Base, LokyStackerV8AutoBestStacking, LokyStackerV8AutoBestBase
from tscglue.old_models import StackerV4, LokyStackerV5, LokyStackerV5SoftRF, LokyStackerV6
from tscglue import utils, data_loader
import polars as pl

In [2]:
dataset = "Worms"
# dataset = 'Car'
# dataset = 'HandOutlines'
# dataset = 'UWaveGestureLibraryY'
X_train, y_train, X_test, y_test = data_loader.load_fold(dataset, 0)
print(X_train.shape, y_train.shape, X_test.shape, y_test.shape)

(181, 1, 900) (181,) (77, 1, 900) (77,)

In [3]:
#m = TSCGlue(random_state=492, n_repetitions=1, n_jobs=16, keep_features=True, verbose=2)
#m.fit(X_train, y_train)
#y_pred = m.predict(X_test)

In [4]:
m = LokyStackerV8Base(random_state=492, n_repetitions=2, n_jobs=16, keep_features=True, verbose=2)
m.fit(X_train, y_train)

[0.00s] Starting executor with 16 workers, run_dir=./tscglue_runs/653c6d68613c456c
[0.00s] Saved X and y to disk in 0.00s
[0.35s] Computed QUANT features (181, 7987) (11.03 MB) in 0.3520s
[0.39s] Starting repetition 0
[2.27s] Computed MultiRocket features (181, 49728) (68.67 MB) in 1.8805s
[4.28s] Computed Hydra features (181, 7168) (9.90 MB) in 2.0069s
[12.11s] Computed RDST features (181, 30000) (41.43 MB) in 7.8285s
[12.11s] Starting training with 16 workers for 40 models
[12.93s] Trained multirockethydra-bestk-p-ridgecv_r0 in 0.8131s for f-3/r-0 (3.06 MB)
[12.94s] Trained multirockethydra-bestk-p-ridgecv_r0 in 0.8201s for f-0/r-0 (3.06 MB)
[12.94s] Trained multirockethydra-bestk-p-ridgecv_r0 in 0.8228s for f-6/r-0 (3.06 MB)
[12.94s] Trained multirockethydra-bestk-p-ridgecv_r0 in 0.8238s for f-9/r-0 (3.06 MB)
[13.00s] Trained multirockethydra-bestk-p-ridgecv_r0 in 0.8836s for f-5/r-0 (3.06 MB)
[13.01s] Trained multirockethydra-bestk-p-ridgecv_r0 in 0.8924s for f-1/r-0 (3.06 MB)
[13.01s] Trained multirockethydra-bestk-p-ridgecv_r0 in 0.8928s for f-4/r-0 (3.06 MB)
[13.02s] Trained multirockethydra-bestk-p-ridgecv_r0 in 0.9033s for f-2/r-0 (3.06 MB)
[13.04s] Trained multirockethydra-bestk-p-ridgecv_r0 in 0.9175s for f-8/r-0 (3.06 MB)
[13.04s] Trained multirockethydra-bestk-p-ridgecv_r0 in 0.9188s for f-7/r-0 (3.06 MB)
[13.04s] Completed training for model multirockethydra-bestk-p-ridgecv_r0
[13.04s] OOF acc for model multirockethydra-bestk-p-ridgecv_r0: 0.7569060773480663
[13.28s] Trained rdst-p-ridgecv_r0 in 0.2711s for f-0/r-0 (1.83 MB)
[13.29s] Trained rdst-p-ridgecv_r0 in 0.2781s for f-1/r-0 (1.83 MB)
[13.30s] Trained rdst-p-ridgecv_r0 in 0.2843s for f-2/r-0 (1.83 MB)
[13.31s] Trained rdst-p-ridgecv_r0 in 0.2825s for f-3/r-0 (1.83 MB)
[13.31s] Trained rdst-p-ridgecv_r0 in 0.2726s for f-4/r-0 (1.83 MB)
[13.33s] Trained rdst-p-ridgecv_r0 in 0.2855s for f-5/r-0 (1.83 MB)
[13.54s] Trained rdst-p-ridgecv_r0 in 0.2621s for f-6/r-0 (1.83 MB)
[13.56s] Trained rdst-p-ridgecv_r0 in 0.2678s for f-7/r-0 (1.83 MB)
[13.57s] Trained rdst-p-ridgecv_r0 in 0.2695s for f-8/r-0 (1.83 MB)
[13.58s] Trained rdst-p-ridgecv_r0 in 0.2695s for f-9/r-0 (1.83 MB)
[13.58s] Completed training for model rdst-p-ridgecv_r0
[13.58s] OOF acc for model rdst-p-ridgecv_r0: 0.7292817679558011
[15.00s] Trained quant-etc_r0 in 2.8868s for f-5/r-0 (1.26 MB)
[15.10s] Trained quant-etc_r0 in 2.9874s for f-0/r-0 (1.29 MB)
[15.15s] Trained quant-etc_r0 in 3.0309s for f-2/r-0 (1.31 MB)
[15.17s] Trained quant-etc_r0 in 3.0543s for f-3/r-0 (1.33 MB)
[15.22s] Trained quant-etc_r0 in 3.1022s for f-1/r-0 (1.34 MB)
[15.25s] Trained quant-etc_r0 in 3.1291s for f-4/r-0 (1.28 MB)
[15.74s] Trained quant-etc_r0 in 2.7987s for f-7/r-0 (1.31 MB)
[15.75s] Trained quant-etc_r0 in 2.8068s for f-9/r-0 (1.29 MB)
[15.82s] Trained quant-etc_r0 in 2.8879s for f-6/r-0 (1.27 MB)
[15.90s] Trained quant-etc_r0 in 2.9545s for f-8/r-0 (1.33 MB)
[15.90s] Completed training for model quant-etc_r0
[15.90s] OOF acc for model quant-etc_r0: 0.7182320441988951
[20.55s] Trained rstsf_r0 in 7.1987s for f-1/r-0 (1.18 MB)
[20.55s] Trained rstsf_r0 in 6.9989s for f-2/r-0 (1.18 MB)
[20.70s] Trained rstsf_r0 in 7.1099s for f-4/r-0 (1.15 MB)
[20.73s] Trained rstsf_r0 in 7.4045s for f-0/r-0 (1.20 MB)
[20.77s] Trained rstsf_r0 in 7.1758s for f-5/r-0 (1.15 MB)
[20.81s] Trained rstsf_r0 in 7.2298s for f-3/r-0 (1.18 MB)
[22.08s] Trained rstsf_r0 in 7.0600s for f-6/r-0 (1.15 MB)
[22.20s] Trained rstsf_r0 in 7.0134s for f-9/r-0 (1.18 MB)
[22.28s] Trained rstsf_r0 in 7.1154s for f-8/r-0 (1.18 MB)
[22.31s] Trained rstsf_r0 in 7.1888s for f-7/r-0 (1.19 MB)
[22.31s] Completed training for model rstsf_r0
[22.32s] OOF acc for model rstsf_r0: 0.7237569060773481
[22.32s] Completed repetition 0
[22.32s] Starting repetition 1
[23.06s] Computed MultiRocket features (181, 49728) (68.67 MB) in 0.7467s
[24.51s] Computed Hydra features (181, 7168) (9.90 MB) in 1.4454s
[30.49s] Computed RDST features (181, 30000) (41.43 MB) in 5.9765s
[30.49s] Starting training with 16 workers for 40 models
[31.29s] Trained multirockethydra-bestk-p-ridgecv_r1 in 0.7871s for f-8/r-1 (3.06 MB)
[31.29s] Trained multirockethydra-bestk-p-ridgecv_r1 in 0.7932s for f-4/r-1 (3.06 MB)
[31.30s] Trained multirockethydra-bestk-p-ridgecv_r1 in 0.7927s for f-6/r-1 (3.06 MB)
[31.30s] Trained multirockethydra-bestk-p-ridgecv_r1 in 0.7958s for f-7/r-1 (3.06 MB)
[31.31s] Trained multirockethydra-bestk-p-ridgecv_r1 in 0.8028s for f-5/r-1 (3.06 MB)
[31.31s] Trained multirockethydra-bestk-p-ridgecv_r1 in 0.8096s for f-3/r-1 (3.06 MB)
[31.34s] Trained multirockethydra-bestk-p-ridgecv_r1 in 0.8383s for f-2/r-1 (3.06 MB)
[31.35s] Trained multirockethydra-bestk-p-ridgecv_r1 in 0.8433s for f-9/r-1 (3.06 MB)
[31.36s] Trained multirockethydra-bestk-p-ridgecv_r1 in 0.8588s for f-0/r-1 (3.06 MB)
[31.37s] Trained multirockethydra-bestk-p-ridgecv_r1 in 0.8662s for f-1/r-1 (3.06 MB)
[31.37s] Completed training for model multirockethydra-bestk-p-ridgecv_r1
[31.37s] OOF acc for model multirockethydra-bestk-p-ridgecv_r1: 0.7734806629834254
[31.60s] Trained rdst-p-ridgecv_r1 in 0.2620s for f-2/r-1 (1.83 MB)
[31.60s] Trained rdst-p-ridgecv_r1 in 0.2942s for f-0/r-1 (1.83 MB)
[31.62s] Trained rdst-p-ridgecv_r1 in 0.2619s for f-4/r-1 (1.83 MB)
[31.63s] Trained rdst-p-ridgecv_r1 in 0.3123s for f-1/r-1 (1.83 MB)
[31.64s] Trained rdst-p-ridgecv_r1 in 0.2671s for f-5/r-1 (1.83 MB)
[31.65s] Trained rdst-p-ridgecv_r1 in 0.3000s for f-3/r-1 (1.83 MB)
[31.86s] Trained rdst-p-ridgecv_r1 in 0.2559s for f-6/r-1 (1.83 MB)
[31.88s] Trained rdst-p-ridgecv_r1 in 0.2563s for f-8/r-1 (1.83 MB)
[31.89s] Trained rdst-p-ridgecv_r1 in 0.2876s for f-7/r-1 (1.83 MB)
[31.92s] Trained rdst-p-ridgecv_r1 in 0.2857s for f-9/r-1 (1.83 MB)
[31.92s] Completed training for model rdst-p-ridgecv_r1
[31.92s] OOF acc for model rdst-p-ridgecv_r1: 0.7237569060773481
[33.51s] Trained quant-etc_r1 in 3.0103s for f-0/r-1 (1.28 MB)
[33.55s] Trained quant-etc_r1 in 3.0507s for f-4/r-1 (1.29 MB)
[33.58s] Trained quant-etc_r1 in 3.0860s for f-2/r-1 (1.33 MB)
[33.68s] Trained quant-etc_r1 in 3.1789s for f-1/r-1 (1.32 MB)
[33.70s] Trained quant-etc_r1 in 3.1963s for f-3/r-1 (1.32 MB)
[33.74s] Trained quant-etc_r1 in 3.2439s for f-5/r-1 (1.29 MB)
[34.12s] Trained quant-etc_r1 in 2.8250s for f-8/r-1 (1.27 MB)
[34.14s] Trained quant-etc_r1 in 2.8508s for f-6/r-1 (1.31 MB)
[34.17s] Trained quant-etc_r1 in 2.8697s for f-7/r-1 (1.32 MB)
[34.22s] Trained quant-etc_r1 in 2.9147s for f-9/r-1 (1.31 MB)
[34.22s] Completed training for model quant-etc_r1
[34.22s] OOF acc for model quant-etc_r1: 0.7071823204419889
[38.72s] Trained rstsf_r1 in 7.0607s for f-1/r-1 (1.17 MB)
[38.79s] Trained rstsf_r1 in 6.8867s for f-3/r-1 (1.18 MB)
[38.89s] Trained rstsf_r1 in 7.0086s for f-2/r-1 (1.18 MB)
[39.02s] Trained rstsf_r1 in 7.0788s for f-5/r-1 (1.14 MB)
[39.03s] Trained rstsf_r1 in 7.3739s for f-0/r-1 (1.18 MB)
[39.28s] Trained rstsf_r1 in 7.3616s for f-4/r-1 (1.18 MB)
[40.17s] Trained rstsf_r1 in 6.5851s for f-8/r-1 (1.16 MB)
[40.28s] Trained rstsf_r1 in 6.7259s for f-7/r-1 (1.18 MB)
[40.45s] Trained rstsf_r1 in 6.9388s for f-6/r-1 (1.19 MB)
[40.58s] Trained rstsf_r1 in 6.8955s for f-9/r-1 (1.18 MB)
[40.58s] Completed training for model rstsf_r1
[40.59s] OOF acc for model rstsf_r1: 0.7237569060773481
[40.59s] Completed repetition 1
[40.59s] Starting stacking model training (single pass)
[40.61s] Trained probability-ridgecv_r0 in 0.0103s for f-2/r-0 (0.00 MB)
[40.61s] Trained probability-ridgecv_r0 in 0.0112s for f-4/r-0 (0.00 MB)
[40.61s] Trained probability-ridgecv_r0 in 0.0111s for f-5/r-0 (0.00 MB)
[40.61s] Trained probability-ridgecv_r1 in 0.0107s for f-1/r-1 (0.00 MB)
[40.61s] Trained probability-ridgecv_r0 in 0.0113s for f-8/r-0 (0.00 MB)
[40.62s] Trained probability-ridgecv_r0 in 0.0120s for f-3/r-0 (0.00 MB)
[40.62s] Trained probability-ridgecv_r0 in 0.0119s for f-7/r-0 (0.00 MB)
[40.62s] Trained probability-ridgecv_r0 in 0.0120s for f-9/r-0 (0.00 MB)
[40.62s] Trained probability-ridgecv_r1 in 0.0121s for f-4/r-1 (0.00 MB)
[40.62s] Trained probability-ridgecv_r1 in 0.0126s for f-0/r-1 (0.00 MB)
[40.62s] Trained probability-ridgecv_r1 in 0.0123s for f-5/r-1 (0.00 MB)
[40.62s] Trained probability-ridgecv_r0 in 0.0165s for f-6/r-0 (0.00 MB)
[40.62s] Trained probability-ridgecv_r1 in 0.0082s for f-6/r-1 (0.00 MB)
[40.62s] Trained probability-ridgecv_r1 in 0.0090s for f-7/r-1 (0.00 MB)
[40.62s] Trained probability-ridgecv_r1 in 0.0080s for f-9/r-1 (0.00 MB)
[40.63s] Trained probability-ridgecv_r1 in 0.0268s for f-2/r-1 (0.00 MB)
[40.63s] Trained probability-ridgecv_r1 in 0.0268s for f-3/r-1 (0.00 MB)
[40.63s] Trained probability-ridgecv_r0 in 0.0299s for f-0/r-0 (0.00 MB)
[40.63s] Trained probability-ridgecv_r0 in 0.0309s for f-1/r-0 (0.00 MB)
[40.63s] Completed training for model probability-ridgecv_r0
[40.63s] OOF acc for model probability-ridgecv_r0: 0.7513812154696132
[40.64s] Trained probability-ridgecv_r1 in 0.0151s for f-8/r-1 (0.00 MB)
[40.64s] Completed training for model probability-ridgecv_r1
[40.64s] OOF acc for model probability-ridgecv_r1: 0.7513812154696132
[41.85s] Trained probability-et_r1 in 1.2048s for f-0/r-1 (10.59 MB)
[41.85s] Trained probability-et_r1 in 1.2102s for f-1/r-1 (10.77 MB)
[41.85s] Trained probability-et_r0 in 1.2119s for f-8/r-0 (10.92 MB)
[41.86s] Trained probability-et_r0 in 1.2171s for f-5/r-0 (9.92 MB)
[41.86s] Trained probability-et_r1 in 1.2176s for f-3/r-1 (10.97 MB)
[41.86s] Trained probability-et_r0 in 1.2191s for f-4/r-0 (10.63 MB)
[41.86s] Trained probability-et_r1 in 1.2203s for f-2/r-1 (10.96 MB)
[41.86s] Trained probability-et_r0 in 1.2204s for f-9/r-0 (10.65 MB)
[41.86s] Trained probability-et_r0 in 1.2223s for f-0/r-0 (10.69 MB)
[41.88s] Trained probability-et_r0 in 1.2375s for f-6/r-0 (10.42 MB)
[41.88s] Trained probability-et_r1 in 1.2371s for f-5/r-1 (10.58 MB)
[41.89s] Trained probability-et_r0 in 1.2441s for f-1/r-0 (10.91 MB)
[41.89s] Trained probability-et_r0 in 1.2445s for f-2/r-0 (10.81 MB)
[41.89s] Trained probability-et_r1 in 1.2503s for f-4/r-1 (10.59 MB)
[41.93s] Trained probability-et_r0 in 1.2931s for f-7/r-0 (11.08 MB)
[41.94s] Trained probability-et_r0 in 1.3033s for f-3/r-0 (10.90 MB)
[41.95s] Completed training for model probability-et_r0
[41.95s] OOF acc for model probability-et_r0: 0.7569060773480663
[43.00s] Trained probability-et_r1 in 1.1436s for f-7/r-1 (10.73 MB)
[43.01s] Trained probability-et_r1 in 1.1581s for f-6/r-1 (10.67 MB)
[43.06s] Trained probability-et_r1 in 1.2046s for f-8/r-1 (10.37 MB)
[43.09s] Trained probability-et_r1 in 1.2344s for f-9/r-1 (11.00 MB)
[43.10s] Completed training for model probability-et_r1
[43.10s] OOF acc for model probability-et_r1: 0.7790055248618785
[43.47s] Trained probability-rf_r0 in 0.3660s for f-3/r-0 (0.99 MB)
[43.47s] Trained probability-rf_r1 in 0.3670s for f-3/r-1 (1.01 MB)
[43.47s] Trained probability-rf_r0 in 0.3696s for f-2/r-0 (0.98 MB)
[43.47s] Trained probability-rf_r0 in 0.3697s for f-0/r-0 (0.97 MB)
[43.47s] Trained probability-rf_r0 in 0.3704s for f-5/r-0 (0.91 MB)
[43.48s] Trained probability-rf_r0 in 0.3712s for f-4/r-0 (0.97 MB)
[43.48s] Trained probability-rf_r1 in 0.3715s for f-2/r-1 (1.01 MB)
[43.48s] Trained probability-rf_r1 in 0.3718s for f-4/r-1 (0.99 MB)
[43.48s] Trained probability-rf_r0 in 0.3736s for f-1/r-0 (1.00 MB)
[43.48s] Trained probability-rf_r1 in 0.3730s for f-0/r-1 (0.97 MB)
[43.48s] Trained probability-rf_r1 in 0.3743s for f-5/r-1 (0.96 MB)
[43.48s] Trained probability-rf_r0 in 0.3752s for f-7/r-0 (1.01 MB)
[43.48s] Trained probability-rf_r0 in 0.3762s for f-6/r-0 (0.95 MB)
[43.49s] Trained probability-rf_r0 in 0.3808s for f-9/r-0 (0.98 MB)
[43.49s] Trained probability-rf_r0 in 0.3835s for f-8/r-0 (1.00 MB)
[43.49s] Completed training for model probability-rf_r0
[43.49s] OOF acc for model probability-rf_r0: 0.7790055248618785
[43.49s] Trained probability-rf_r1 in 0.3881s for f-1/r-1 (0.97 MB)
[43.84s] Trained probability-rf_r1 in 0.3711s for f-6/r-1 (0.99 MB)
[43.84s] Trained probability-rf_r1 in 0.3688s for f-8/r-1 (0.96 MB)
[43.84s] Trained probability-rf_r1 in 0.3693s for f-9/r-1 (1.01 MB)
[43.85s] Trained probability-rf_r1 in 0.3733s for f-7/r-1 (0.96 MB)
[43.85s] Completed training for model probability-rf_r1
[43.85s] OOF acc for model probability-rf_r1: 0.7900552486187845
[43.85s] Completed all repetitions and stacking
[43.85s] Executor shutdown complete

LokyStackerV8Base(keep_features=True, n_jobs=16, n_repetitions=2,
                  random_state=492, verbose=2)

In [5]:
preds = m.predict_per_model(X_test)
tests_accs = []
for model_name, model_preds in preds.items():
    acc = accuracy_score(y_test, model_preds)
    tests_accs.append({"model": model_name, "test_accuracy": acc})
test_df = pl.DataFrame(tests_accs)

[0.0000s] Starting prediction
Starting executor with 16 workers, run_dir=./tscglue_runs/653c6d68613c456c
[6.2444s] Computed features for prediction
[6.2915s] Feature arrays saved to mmap files
[6.2916s] Starting prediction with 16 workers for 80 first-level models
[13.3535s] Predicted multirockethydra-bestk-p-ridgecv_r1 in 0.0951s
[13.3952s] Predicted multirockethydra-bestk-p-ridgecv_r0 in 0.1023s
[13.4534s] Predicted multirockethydra-bestk-p-ridgecv_r1 in 0.0956s
[13.4985s] Predicted multirockethydra-bestk-p-ridgecv_r1 in 0.0984s
[13.5521s] Predicted multirockethydra-bestk-p-ridgecv_r1 in 0.1067s
[13.5546s] Predicted multirockethydra-bestk-p-ridgecv_r1 in 0.0962s
[13.5894s] Predicted quant-etc_r0 in 0.0206s
[13.5923s] Predicted quant-etc_r0 in 0.0246s
[13.6008s] Predicted multirockethydra-bestk-p-ridgecv_r1 in 0.0980s
[13.6224s] Predicted quant-etc_r0 in 0.0203s
[13.6321s] Predicted quant-etc_r0 in 0.0230s
[13.6366s] Predicted multirockethydra-bestk-p-ridgecv_r0 in 0.1239s
[13.6427s] Predicted quant-etc_r0 in 0.0238s
[13.6556s] Predicted quant-etc_r0 in 0.0200s
[13.6671s] Predicted quant-etc_r0 in 0.0224s
[13.6681s] Predicted multirockethydra-bestk-p-ridgecv_r1 in 0.1073s
[13.6784s] Predicted quant-etc_r0 in 0.0219s
[13.6814s] Predicted quant-etc_r0 in 0.0242s
[13.6871s] Predicted quant-etc_r0 in 0.0201s
[13.6918s] Predicted quant-etc_r1 in 0.0157s
[13.7041s] Predicted quant-etc_r1 in 0.0218s
[13.7062s] Predicted multirockethydra-bestk-p-ridgecv_r0 in 0.1169s
[13.7171s] Predicted multirockethydra-bestk-p-ridgecv_r0 in 0.1155s
[13.7188s] Predicted multirockethydra-bestk-p-ridgecv_r0 in 0.1317s
[13.7235s] Predicted multirockethydra-bestk-p-ridgecv_r0 in 0.1241s
[13.7258s] Predicted quant-etc_r1 in 0.0233s
[13.7275s] Predicted quant-etc_r1 in 0.0283s
[13.7364s] Predicted quant-etc_r1 in 0.0224s
[13.7383s] Predicted quant-etc_r1 in 0.0245s
[13.7496s] Predicted quant-etc_r1 in 0.0315s
[13.7601s] Predicted rdst-p-ridgecv_r0 in 0.0357s
[13.7749s] Predicted rdst-p-ridgecv_r0 in 0.0362s
[13.7801s] Predicted rdst-p-ridgecv_r0 in 0.0494s
[13.7854s] Predicted rdst-p-ridgecv_r0 in 0.0609s
[13.7900s] Predicted rdst-p-ridgecv_r0 in 0.0554s
[13.7917s] Predicted quant-etc_r1 in 0.0502s
[13.7987s] Predicted quant-etc_r1 in 0.0469s
[13.8081s] Predicted rdst-p-ridgecv_r0 in 0.0331s
[13.8105s] Predicted multirockethydra-bestk-p-ridgecv_r0 in 0.1102s
[13.8181s] Predicted quant-etc_r1 in 0.0637s
[13.8265s] Predicted rdst-p-ridgecv_r0 in 0.0583s
[13.8341s] Predicted rdst-p-ridgecv_r0 in 0.0749s
[13.8375s] Predicted rdst-p-ridgecv_r0 in 0.0518s
[13.8498s] Predicted rdst-p-ridgecv_r1 in 0.0357s
[13.8515s] Predicted rdst-p-ridgecv_r1 in 0.0493s
[13.8581s] Predicted rdst-p-ridgecv_r1 in 0.0433s
[13.8771s] Predicted rdst-p-ridgecv_r1 in 0.0457s
[13.8788s] Predicted rdst-p-ridgecv_r1 in 0.0765s
[13.8816s] Predicted rdst-p-ridgecv_r1 in 0.0770s
[13.8941s] Predicted rdst-p-ridgecv_r0 in 0.0991s
[13.8958s] Predicted multirockethydra-bestk-p-ridgecv_r0 in 0.1224s
[13.9043s] Predicted rdst-p-ridgecv_r1 in 0.0531s
[13.9160s] Predicted rdst-p-ridgecv_r1 in 0.0712s
[13.9183s] Predicted rdst-p-ridgecv_r1 in 0.0789s
[13.9240s] Predicted rdst-p-ridgecv_r1 in 0.0878s
[13.9831s] Predicted multirockethydra-bestk-p-ridgecv_r1 in 0.1910s
[14.0608s] Predicted multirockethydra-bestk-p-ridgecv_r1 in 0.1526s
[14.1083s] Predicted multirockethydra-bestk-p-ridgecv_r0 in 0.1200s
[14.2039s] Predicted multirockethydra-bestk-p-ridgecv_r1 in 0.1194s
[14.3454s] Predicted multirockethydra-bestk-p-ridgecv_r0 in 0.0966s
[32.1266s] Predicted rstsf_r1 in 17.9940s
[32.2372s] Predicted rstsf_r0 in 18.2985s
[32.3107s] Predicted rstsf_r0 in 18.3728s
[32.3307s] Predicted rstsf_r0 in 18.3795s
[32.3647s] Predicted rstsf_r1 in 18.2797s
[32.3708s] Predicted rstsf_r0 in 18.4369s
[32.3960s] Predicted rstsf_r0 in 18.4783s
[32.4250s] Predicted rstsf_r0 in 18.5436s
[32.4657s] Predicted rstsf_r0 in 18.4838s
[32.4881s] Predicted rstsf_r0 in 18.5547s
[32.5003s] Predicted rstsf_r0 in 18.5709s
[32.5483s] Predicted rstsf_r1 in 18.5261s
[32.5584s] Predicted rstsf_r0 in 18.6328s
[32.6076s] Predicted rstsf_r1 in 18.3800s
[32.6104s] Predicted rstsf_r1 in 0.3605s
[32.9686s] Predicted rstsf_r1 in 18.6076s
[33.5508s] Predicted rstsf_r1 in 19.5607s
[40.5645s] Predicted rstsf_r1 in 8.2199s
[40.9274s] Predicted rstsf_r1 in 8.6010s
[41.0355s] Predicted rstsf_r1 in 8.8943s
[42.8466s] Completed all first-level model predictions
[42.9560s] Starting prediction with 16 workers for 60 stacking models
[49.6592s] Predicted probability-ridgecv in 0.0014s
[49.6625s] Predicted probability-ridgecv in 0.0010s
[49.6645s] Predicted probability-ridgecv in 0.0012s
[49.6666s] Predicted probability-ridgecv in 0.0011s
[49.6691s] Predicted probability-ridgecv in 0.0011s
[49.7022s] Predicted probability-ridgecv in 0.0014s
[49.7060s] Predicted probability-ridgecv in 0.0015s
[49.7951s] Predicted probability-et in 0.0650s
[49.8219s] Predicted probability-ridgecv in 0.0014s
[49.8280s] Predicted probability-ridgecv in 0.0014s
[49.8376s] Predicted probability-et in 0.0656s
[49.8405s] Predicted probability-et in 0.0713s
[49.8573s] Predicted probability-ridgecv in 0.0013s
[49.8772s] Predicted probability-ridgecv in 0.0016s
[49.9055s] Predicted probability-et in 0.0644s
[49.9488s] Predicted probability-ridgecv in 0.0021s
[49.9528s] Predicted probability-et in 0.0634s
[49.9592s] Predicted probability-ridgecv in 0.0018s
[49.9617s] Predicted probability-et in 0.0642s
[49.9643s] Predicted probability-et in 0.0682s
[49.9691s] Predicted probability-et in 0.0783s
[49.9715s] Predicted probability-ridgecv in 0.0015s
[49.9954s] Predicted probability-et in 0.0733s
[50.0031s] Predicted probability-et in 0.0639s
[50.0133s] Predicted probability-et in 0.0635s
[50.0335s] Predicted probability-rf in 0.0124s
[50.0583s] Predicted probability-ridgecv in 0.0016s
[50.0610s] Predicted probability-et in 0.0627s
[50.0634s] Predicted probability-rf in 0.0195s
[50.0664s] Predicted probability-et in 0.0638s
[50.0764s] Predicted probability-et in 0.0651s
[50.0796s] Predicted probability-rf in 0.0124s
[50.0823s] Predicted probability-rf in 0.0123s
[50.0847s] Predicted probability-et in 0.0631s
[50.0869s] Predicted probability-rf in 0.0121s
[50.0893s] Predicted probability-rf in 0.0119s
[50.0915s] Predicted probability-ridgecv in 0.0015s
[50.0939s] Predicted probability-et in 0.0724s
[50.0965s] Predicted probability-et in 0.0633s
[50.0989s] Predicted probability-rf in 0.0130s
[50.1014s] Predicted probability-rf in 0.0123s
[50.1037s] Predicted probability-rf in 0.0119s
[50.1061s] Predicted probability-rf in 0.0123s
[50.1083s] Predicted probability-rf in 0.0121s
[50.1099s] Predicted probability-rf in 0.0119s
[50.1115s] Predicted probability-et in 0.0610s
[50.1124s] Predicted probability-et in 0.0780s
[50.1133s] Predicted probability-et in 0.0636s
[50.1142s] Predicted probability-rf in 0.0128s
[50.1163s] Predicted probability-rf in 0.0140s
[50.1175s] Predicted probability-rf in 0.0128s
[50.1187s] Predicted probability-rf in 0.0127s
[50.1199s] Predicted probability-rf in 0.0117s
[50.1208s] Predicted probability-rf in 0.0124s
[50.1220s] Predicted probability-rf in 0.0119s
[50.1233s] Predicted probability-rf in 0.0119s
[50.1453s] Predicted probability-ridgecv in 0.0015s
[50.1831s] Predicted probability-ridgecv in 0.0014s
[50.1956s] Predicted probability-ridgecv in 0.0016s
[50.3222s] Predicted probability-ridgecv in 0.0016s
[51.6934s] Completed all stacking model predictions
Executor shutdown complete

In [9]:
preds.keys()

dict_keys(['multirockethydra-bestk-p-ridgecv_r0', 'multirockethydra-bestk-p-ridgecv_r1', 'quant-etc_r0', 'quant-etc_r1', 'rdst-p-ridgecv_r0', 'rdst-p-ridgecv_r1', 'rstsf_r0', 'rstsf_r1', 'probability-ridgecv', 'probability-et', 'probability-rf'])

In [6]:
pl.DataFrame(m.summary())

shape: (14, 3)
┌─────────────────────────────────┬───────┬──────────────┐
│ model                           ┆ level ┆ oof_accuracy │
│ ---                             ┆ ---   ┆ ---          │
│ str                             ┆ i64   ┆ f64          │
╞═════════════════════════════════╪═══════╪══════════════╡
│ multirockethydra-bestk-p-ridge… ┆ 0     ┆ 0.756906     │
│ rdst-p-ridgecv_r0               ┆ 0     ┆ 0.729282     │
│ quant-etc_r0                    ┆ 0     ┆ 0.718232     │
│ rstsf_r0                        ┆ 0     ┆ 0.723757     │
│ multirockethydra-bestk-p-ridge… ┆ 0     ┆ 0.773481     │
│ …                               ┆ …     ┆ …            │
│ probability-ridgecv_r1          ┆ 1     ┆ 0.751381     │
│ probability-et_r0               ┆ 1     ┆ 0.756906     │
│ probability-et_r1               ┆ 1     ┆ 0.779006     │
│ probability-rf_r0               ┆ 1     ┆ 0.779006     │
│ probability-rf_r1               ┆ 1     ┆ 0.790055     │
└─────────────────────────────────┴───────┴──────────────┘

In [7]:
pl.DataFrame(m.summary()).join(test_df, on="model").sort("test_accuracy", descending=True)

shape: (8, 4)
┌─────────────────────────────────┬───────┬──────────────┬───────────────┐
│ model                           ┆ level ┆ oof_accuracy ┆ test_accuracy │
│ ---                             ┆ ---   ┆ ---          ┆ ---           │
│ str                             ┆ i64   ┆ f64          ┆ f64           │
╞═════════════════════════════════╪═══════╪══════════════╪═══════════════╡
│ multirockethydra-bestk-p-ridge… ┆ 0     ┆ 0.756906     ┆ 0.805195      │
│ rstsf_r0                        ┆ 0     ┆ 0.723757     ┆ 0.792208      │
│ rstsf_r1                        ┆ 0     ┆ 0.723757     ┆ 0.792208      │
│ multirockethydra-bestk-p-ridge… ┆ 0     ┆ 0.773481     ┆ 0.779221      │
│ quant-etc_r1                    ┆ 0     ┆ 0.707182     ┆ 0.779221      │
│ quant-etc_r0                    ┆ 0     ┆ 0.718232     ┆ 0.766234      │
│ rdst-p-ridgecv_r1               ┆ 0     ┆ 0.723757     ┆ 0.714286      │
│ rdst-p-ridgecv_r0               ┆ 0     ┆ 0.729282     ┆ 0.688312      │
└─────────────────────────────────┴───────┴──────────────┴───────────────┘

In [8]:
sfsf=efwef

NameError: name 'efwef' is not defined

In [ ]:
y_pred = m.predict(X_test)
acc = accuracy_score(y_test, y_pred)
print(f"Accuracy on {dataset}: {acc}")

In [ ]:
F = m.get_features()
F.estimated_size('gb')

In [ ]:
P = m.get_oof_predictions()
P.estimated_size('gb')

In [ ]:
m = LokyStackerV6(random_state=492, n_repetitions=1, n_jobs=16)
m.fit(X_train, y_train)

In [ ]:
y_pred = m.predict(X_test)
acc = accuracy_score(y_test, y_pred)
print(f"Accuracy on {dataset}: {acc}")

In [ ]:
m = LokyStackerV5(random_state=492, n_repetitions=1, n_jobs=16)
m.fit(X_train, y_train)

In [ ]:
y_pred = m.predict(X_test)
acc = accuracy_score(y_test, y_pred)
print(f"Accuracy on {dataset}: {acc}")