In [1]:
import numpy as np
from aeon.classification.interval_based import RSTSF
from sklearn.metrics import accuracy_score
from autotsc.models import StackerV4, LokyStackerV5, LokyStackerV5SoftRF, LokyStackerV6, LokyStackerV7
from autotsc import utils

In [2]:
dataset = "Worms"
dataset = 'HandOutlines'
# dataset = 'Car'
X_train, y_train, X_test, y_test = utils.load_dataset(dataset)
print(X_train.shape, y_train.shape, X_test.shape, y_test.shape)
# print(X_train.dtype)
# print(y_train.dtype)

(1000, 1, 2709) (1000,) (370, 1, 2709) (370,)

In [3]:
m = LokyStackerV7(random_state=492, n_repetitions=1, n_jobs=16, keep_features=True)
m.fit(X_train, y_train)

[0.0000s] Starting fitting (n_repetitions=1, k_folds=10, keep_features=True)
Starting executor with 16 workers, run_dir=./tscglue/12737766833f4797
[6.7462s] Computed QUANT features (1000, 24015) (183.22 MB) in 6.7450s
[6.7883s] Starting repetition 0
[21.7927s] Computed MultiRocket features (1000, 49728) (379.39 MB) in 15.0041s
[222.3140s] Computed Hydra features (1000, 9216) (70.31 MB) in 200.5208s
[345.9681s] Computed RDST features (1000, 30000) (228.88 MB) in 123.6419s
[345.9843s] Starting training with 16 workers for 40 models
[381.9161s] Trained multirockethydra-ridgecv_r0 in 22.8974s for f-0/r-0 (1.80 MB)
[385.5677s] Trained multirockethydra-ridgecv_r0 in 19.8424s for f-7/r-0 (1.80 MB)
[386.5804s] Trained multirockethydra-ridgecv_r0 in 22.5332s for f-9/r-0 (1.80 MB)
[386.9951s] Trained multirockethydra-ridgecv_r0 in 24.0388s for f-2/r-0 (1.80 MB)
[387.0249s] Trained multirockethydra-ridgecv_r0 in 22.9859s for f-5/r-0 (1.80 MB)
[389.2682s] Trained multirockethydra-ridgecv_r0 in 23.2358s for f-8/r-0 (1.80 MB)
[390.1034s] Trained multirockethydra-ridgecv_r0 in 24.1156s for f-1/r-0 (1.80 MB)
[390.2742s] Trained multirockethydra-ridgecv_r0 in 23.7864s for f-4/r-0 (1.80 MB)
[390.3903s] Trained multirockethydra-ridgecv_r0 in 24.0740s for f-3/r-0 (1.80 MB)
[393.8818s] Trained multirockethydra-ridgecv_r0 in 32.6024s for f-6/r-0 (1.80 MB)
[393.8832s] Completed training for model multirockethydra-ridgecv_r0
[393.9092s] OOF acc for model multirockethydra-ridgecv_r0: 0.957
[396.7184s] Trained rdst-ridgecv_r0 in 9.1591s for f-0/r-0 (0.92 MB)
[397.3316s] Trained rdst-ridgecv_r0 in 7.6227s for f-1/r-0 (0.92 MB)
[398.3931s] Trained rdst-ridgecv_r0 in 7.6789s for f-4/r-0 (0.92 MB)
[399.0920s] Trained rdst-ridgecv_r0 in 8.4807s for f-2/r-0 (0.92 MB)
[399.1032s] Trained rdst-ridgecv_r0 in 8.3734s for f-3/r-0 (0.92 MB)
[401.0836s] Trained rdst-ridgecv_r0 in 6.3282s for f-5/r-0 (0.92 MB)
[408.4445s] Trained rdst-ridgecv_r0 in 9.4458s for f-7/r-0 (0.92 MB)
[408.8355s] Trained rdst-ridgecv_r0 in 7.3913s for f-6/r-0 (0.92 MB)
[409.4687s] Trained rdst-ridgecv_r0 in 9.8932s for f-8/r-0 (0.92 MB)
[411.5139s] Trained rdst-ridgecv_r0 in 10.3273s for f-9/r-0 (0.92 MB)
[411.5195s] Completed training for model rdst-ridgecv_r0
[411.5376s] OOF acc for model rdst-ridgecv_r0: 0.951
[471.0261s] Trained quant-etc_r0 in 102.8538s for f-4/r-0 (1.67 MB)
[476.2468s] Trained quant-etc_r0 in 89.4172s for f-8/r-0 (1.70 MB)
[480.8107s] Trained quant-etc_r0 in 93.5655s for f-9/r-0 (1.73 MB)
[498.8017s] Trained rstsf_r0 in 97.6468s for f-1/r-0 (1.81 MB)
[499.2468s] Trained quant-etc_r0 in 132.1247s for f-2/r-0 (1.64 MB)
[507.2460s] Trained rstsf_r0 in 97.0282s for f-3/r-0 (1.77 MB)
[513.7023s] Trained quant-etc_r0 in 131.4473s for f-6/r-0 (1.72 MB)
[516.4929s] Trained quant-etc_r0 in 130.6518s for f-7/r-0 (1.72 MB)
[541.8562s] Trained rstsf_r0 in 132.3659s for f-4/r-0 (1.77 MB)
[548.0098s] Trained rstsf_r0 in 76.9603s for f-6/r-0 (1.79 MB)
[550.2827s] Trained rstsf_r0 in 74.0110s for f-7/r-0 (1.79 MB)
[553.1398s] Trained rstsf_r0 in 144.6770s for f-2/r-0 (1.74 MB)
[556.2285s] Trained rstsf_r0 in 75.3976s for f-8/r-0 (1.80 MB)
[568.2558s] Trained rstsf_r0 in 169.0857s for f-0/r-0 (1.83 MB)
[570.6939s] Trained rstsf_r0 in 71.8879s for f-9/r-0 (1.78 MB)
[579.3860s] Trained rstsf_r0 in 167.8105s for f-5/r-0 (1.84 MB)
[579.3873s] Completed training for model rstsf_r0
[579.3941s] OOF acc for model rstsf_r0: 0.899
[583.9213s] Trained quant-etc_r0 in 221.0829s for f-0/r-0 (1.66 MB)
[586.5065s] Trained quant-etc_r0 in 223.2703s for f-3/r-0 (1.70 MB)
[587.0300s] Trained quant-etc_r0 in 221.4735s for f-5/r-0 (1.75 MB)
[602.2630s] Trained quant-etc_r0 in 236.9624s for f-1/r-0 (1.70 MB)
[602.2641s] Completed training for model quant-etc_r0
[602.2670s] OOF acc for model quant-etc_r0: 0.92
[605.3230s] Completed repetition 0
[605.3231s] Starting stacking model training (single pass)
[613.8116s] Trained probability-ridgecv in 0.0224s for f-0 (0.00 MB)
[614.5206s] Trained probability-ridgecv in 0.0330s for f-3 (0.00 MB)
[614.7323s] Trained probability-ridgecv in 0.0242s for f-1 (0.00 MB)
[614.8198s] Trained probability-ridgecv in 0.0285s for f-7 (0.00 MB)
[614.8341s] Trained probability-ridgecv in 0.0292s for f-6 (0.00 MB)
[614.8368s] Trained probability-ridgecv in 0.0302s for f-2 (0.00 MB)
[614.8611s] Trained probability-ridgecv in 0.0297s for f-8 (0.00 MB)
[614.8718s] Trained probability-ridgecv in 0.0310s for f-4 (0.00 MB)
[614.9176s] Trained probability-ridgecv in 0.0214s for f-9 (0.00 MB)
[615.0961s] Trained probability-ridgecv in 0.0221s for f-5 (0.00 MB)
[619.3617s] OOF acc for model probability-ridgecv: 0.956
[619.3619s] Completed all repetitions and stacking
Executor shutdown complete

LokyStackerV7(keep_features=True, n_jobs=16, random_state=492)

In [4]:
y_pred = m.predict(X_test)
acc = accuracy_score(y_test, y_pred)
print(f"Accuracy on {dataset}: {acc}")

[0.0000s] Starting prediction
Starting executor with 16 workers, run_dir=./tscglue/12737766833f4797
[71.2613s] Computed features for prediction
[71.8164s] Feature arrays saved to mmap files
[71.8168s] Starting prediction with 16 workers for 40 first-level models
[81.8091s] Predicted quant-etc_r0 in 0.0370s
[81.9964s] Predicted quant-etc_r0 in 0.1021s
[82.0146s] Predicted quant-etc_r0 in 0.0966s
[82.0205s] Predicted quant-etc_r0 in 0.0585s
[82.0543s] Predicted quant-etc_r0 in 0.0521s
[82.0573s] Predicted quant-etc_r0 in 0.0963s
[82.3326s] Predicted rdst-ridgecv_r0 in 0.2622s
[82.5140s] Predicted quant-etc_r0 in 0.0921s
[82.5174s] Predicted rdst-ridgecv_r0 in 0.4232s
[82.6284s] Predicted quant-etc_r0 in 0.1036s
[82.6835s] Predicted rdst-ridgecv_r0 in 0.3293s
[82.8430s] Predicted rdst-ridgecv_r0 in 0.3126s
[82.9745s] Predicted rdst-ridgecv_r0 in 0.3271s
[82.9776s] Predicted rdst-ridgecv_r0 in 0.4377s
[82.9907s] Predicted rdst-ridgecv_r0 in 0.2878s
[83.0744s] Predicted quant-etc_r0 in 0.1398s
[83.1207s] Predicted rdst-ridgecv_r0 in 0.2564s
[83.2177s] Predicted rdst-ridgecv_r0 in 0.2190s
[83.2649s] Predicted quant-etc_r0 in 0.1299s
[83.3368s] Predicted multirockethydra-ridgecv_r0 in 0.3166s
[83.4071s] Predicted rdst-ridgecv_r0 in 0.4031s
[83.5115s] Predicted multirockethydra-ridgecv_r0 in 0.3645s
[83.6163s] Predicted multirockethydra-ridgecv_r0 in 0.3663s
[83.7353s] Predicted multirockethydra-ridgecv_r0 in 0.3633s
[83.8585s] Predicted multirockethydra-ridgecv_r0 in 0.7338s
[83.9280s] Predicted multirockethydra-ridgecv_r0 in 0.3860s
[84.0116s] Predicted multirockethydra-ridgecv_r0 in 0.7029s
[84.0300s] Predicted multirockethydra-ridgecv_r0 in 0.3826s
[84.1498s] Predicted multirockethydra-ridgecv_r0 in 0.3776s
[84.1890s] Predicted multirockethydra-ridgecv_r0 in 0.7432s
[104.9386s] Predicted rstsf_r0 in 22.9004s
[105.0294s] Predicted rstsf_r0 in 23.1192s
[106.3548s] Predicted rstsf_r0 in 24.4313s
[106.4269s] Predicted rstsf_r0 in 24.5278s
[108.9501s] Predicted rstsf_r0 in 26.6821s
[109.2581s] Predicted rstsf_r0 in 27.2227s
[122.5018s] Predicted rstsf_r0 in 40.8093s
[128.1646s] Predicted rstsf_r0 in 46.1306s
[129.1380s] Predicted rstsf_r0 in 47.3183s
[130.7611s] Predicted rstsf_r0 in 49.1198s
[140.1970s] Completed all first-level model predictions
[140.7742s] Starting prediction with 10 workers for 10 stacking models
[148.4142s] Predicted probability-ridgecv in 0.0030s
[149.8360s] Predicted probability-ridgecv in 0.0039s
[152.8760s] Predicted probability-ridgecv in 0.0036s
[153.4419s] Predicted probability-ridgecv in 0.0042s
[153.8112s] Predicted probability-ridgecv in 0.0048s
[154.3094s] Predicted probability-ridgecv in 0.0043s
[154.5432s] Predicted probability-ridgecv in 0.0043s
[154.7161s] Predicted probability-ridgecv in 0.0047s
[154.8493s] Predicted probability-ridgecv in 0.0034s
[155.7403s] Predicted probability-ridgecv in 0.0037s
[163.6715s] Completed all stacking model predictions
Executor shutdown complete
Accuracy on HandOutlines: 0.9486486486486486

In [5]:
F = m.get_features()
F

shape: (1_000, 112_959)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ hydra_r0| ┆ hydra_r0| ┆ hydra_r0| ┆ hydra_r0| ┆ … ┆ rdst_r0|2 ┆ rdst_r0|2 ┆ rdst_r0|2 ┆ rdst_r0| │
│ 0         ┆ 1         ┆ 2         ┆ 3         ┆   ┆ 9996      ┆ 9997      ┆ 9998      ┆ 29999    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.35671   ┆ 0.16968   ┆ 1.67961   ┆ 9.697312  ┆ … ┆ 74.0      ┆ 0.581289  ┆ 2024.0    ┆ 111.0    │
│ 0.369583  ┆ 0.212441  ┆ 1.385176  ┆ 9.083817  ┆ … ┆ 152.0     ┆ 0.384315  ┆ 2600.0    ┆ 163.0    │
│ 0.307789  ┆ 0.106495  ┆ 1.355328  ┆ 8.279738  ┆ … ┆ 107.0     ┆ 0.347373  ┆ 923.0     ┆ 225.0    │
│ 0.275315  ┆ 0.333093  ┆ 1.38384   ┆ 7.739194  ┆ … ┆ 140.0     ┆ 0.401663  ┆ 2445.0    ┆ 203.0    │
│ 0.287295  ┆ 0.064487  ┆ 1.420782  ┆ 9.566106  ┆ … ┆ 124.0     ┆ 0.436736  ┆ 2643.0    ┆ 182.0    │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 0.126984  ┆ 0.046776  ┆ 1.427749  ┆ 9.038822  ┆ … ┆ 139.0     ┆ 0.392878  ┆ 2628.0    ┆ 197.0    │
│ 0.136578  ┆ 0.069092  ┆ 1.493623  ┆ 9.814469  ┆ … ┆ 144.0     ┆ 0.256717  ┆ 606.0     ┆ 229.0    │
│ 0.146057  ┆ 0.044284  ┆ 1.458489  ┆ 9.569075  ┆ … ┆ 139.0     ┆ 0.346085  ┆ 2637.0    ┆ 153.0    │
│ 0.168711  ┆ 0.067231  ┆ 1.439931  ┆ 9.063564  ┆ … ┆ 94.0      ┆ 0.370114  ┆ 2632.0    ┆ 218.0    │
│ 0.164255  ┆ 0.080741  ┆ 1.452762  ┆ 9.639206  ┆ … ┆ 141.0     ┆ 0.320362  ┆ 2626.0    ┆ 263.0    │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [6]:
F.estimated_size('gb')

0.8416101336479187

In [7]:
P = m.get_oof_predictions()
P

shape: (1_000, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ multirock ┆ multirock ┆ probabili ┆ probabili ┆ … ┆ rdst-ridg ┆ rdst-ridg ┆ rstsf_r0| ┆ rstsf_r0 │
│ ethydra-r ┆ ethydra-r ┆ ty-ridgec ┆ ty-ridgec ┆   ┆ ecv_r0|0  ┆ ecv_r0|1  ┆ 0         ┆ |1       │
│ idgecv_r0 ┆ idgecv_r0 ┆ v|0       ┆ v|1       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ |0        ┆ |1        ┆ ---       ┆ ---       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
│ ---       ┆ ---       ┆ f64       ┆ f64       ┆   ┆           ┆           ┆           ┆          │
│ f64       ┆ f64       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 1.0       ┆ 0.0       ┆ 1.0       ┆ 0.0       ┆ … ┆ 1.0       ┆ 0.0       ┆ 0.88      ┆ 0.12     │
│ 0.0       ┆ 1.0       ┆ 0.0       ┆ 1.0       ┆ … ┆ 0.0       ┆ 1.0       ┆ 0.49      ┆ 0.51     │
│ 1.0       ┆ 0.0       ┆ 1.0       ┆ 0.0       ┆ … ┆ 1.0       ┆ 0.0       ┆ 0.91      ┆ 0.09     │
│ 1.0       ┆ 0.0       ┆ 1.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 1.0       ┆ 0.94      ┆ 0.06     │
│ 0.0       ┆ 1.0       ┆ 0.0       ┆ 1.0       ┆ … ┆ 0.0       ┆ 1.0       ┆ 0.03      ┆ 0.97     │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 0.0       ┆ 1.0       ┆ 0.0       ┆ 1.0       ┆ … ┆ 0.0       ┆ 1.0       ┆ 0.04      ┆ 0.96     │
│ 0.0       ┆ 1.0       ┆ 0.0       ┆ 1.0       ┆ … ┆ 0.0       ┆ 1.0       ┆ 0.05      ┆ 0.95     │
│ 0.0       ┆ 1.0       ┆ 0.0       ┆ 1.0       ┆ … ┆ 0.0       ┆ 1.0       ┆ 0.01      ┆ 0.99     │
│ 1.0       ┆ 0.0       ┆ 1.0       ┆ 0.0       ┆ … ┆ 1.0       ┆ 0.0       ┆ 0.95      ┆ 0.05     │
│ 1.0       ┆ 0.0       ┆ 1.0       ┆ 0.0       ┆ … ┆ 1.0       ┆ 0.0       ┆ 0.13      ┆ 0.87     │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [8]:
dcsD=sfsf

NameError: name 'sfsf' is not defined

In [9]:
m = LokyStackerV6(random_state=492, n_repetitions=1, n_jobs=16)
m.fit(X_train, y_train)

[0.0001s] Starting fitting
Starting executor with 16 workers, run_dir=./tscglue/ba1a967a4c724985
[5.2623s] Computed QUANT features (1000, 24015) (183.22 MB) in 5.2297s
[5.5534s] Starting repetition 0
[13.0629s] Computed MultiRocket features (1000, 49728) (379.39 MB) in 7.5094s
[446.9471s] Computed Hydra features (1000, 9216) (70.31 MB) in 433.8817s
[584.6001s] Computed RDST features (1000, 30000) (228.88 MB) in 137.5987s
[584.6549s] Starting training with 16 workers for 40 models
[641.6214s] Trained multirockethydra-ridgecv in 47.5500s for f-8/r-0 (1.80 MB)
[643.9870s] Trained multirockethydra-ridgecv in 48.2774s for f-0/r-0 (1.80 MB)
[645.1712s] Trained multirockethydra-ridgecv in 50.8676s for f-1/r-0 (1.80 MB)
[645.8461s] Trained multirockethydra-ridgecv in 46.9343s for f-5/r-0 (1.80 MB)
[646.1663s] Trained multirockethydra-ridgecv in 47.2868s for f-7/r-0 (1.80 MB)
[646.9659s] Trained multirockethydra-ridgecv in 52.3908s for f-2/r-0 (1.80 MB)
[647.0337s] Trained multirockethydra-ridgecv in 52.7981s for f-6/r-0 (1.80 MB)
[647.0585s] Trained multirockethydra-ridgecv in 52.9104s for f-4/r-0 (1.80 MB)
[647.3530s] Trained multirockethydra-ridgecv in 47.9868s for f-9/r-0 (1.80 MB)
[647.8625s] Trained multirockethydra-ridgecv in 52.9073s for f-3/r-0 (1.80 MB)
[647.8646s] Completed training for model multirockethydra-ridgecv
[649.0400s] OOF acc for model multirockethydra-ridgecv: 0.957
[655.4742s] Trained rdst-ridgecv in 8.9438s for f-0/r-0 (0.92 MB)
[657.7278s] Trained rdst-ridgecv in 9.6296s for f-4/r-0 (0.92 MB)
[657.8402s] Trained rdst-ridgecv in 10.1573s for f-1/r-0 (0.92 MB)
[658.0331s] Trained rdst-ridgecv in 10.0859s for f-2/r-0 (0.92 MB)
[658.8829s] Trained rdst-ridgecv in 10.4729s for f-5/r-0 (0.92 MB)
[659.9519s] Trained rdst-ridgecv in 12.1259s for f-3/r-0 (0.92 MB)
[661.7802s] Trained rdst-ridgecv in 5.9216s for f-6/r-0 (0.92 MB)
[662.8715s] Trained rdst-ridgecv in 4.6187s for f-8/r-0 (0.92 MB)
[663.9414s] Trained rdst-ridgecv in 5.5527s for f-9/r-0 (0.92 MB)
[666.0152s] Trained rdst-ridgecv in 7.7941s for f-7/r-0 (0.92 MB)
[666.0171s] Completed training for model rdst-ridgecv
[666.3045s] OOF acc for model rdst-ridgecv: 0.951
[744.9567s] Trained quant-etc in 98.8189s for f-8/r-0 (1.70 MB)
[752.6215s] Trained quant-etc in 106.0599s for f-9/r-0 (1.73 MB)
[762.0731s] Trained rstsf in 100.1445s for f-2/r-0 (1.74 MB)
[762.6159s] Trained quant-etc in 117.8494s for f-7/r-0 (1.72 MB)
[764.6735s] Trained rstsf in 100.5930s for f-4/r-0 (1.77 MB)
[766.8352s] Trained rstsf in 103.8279s for f-3/r-0 (1.77 MB)
[767.9715s] Trained quant-etc in 172.9055s for f-3/r-0 (1.70 MB)
[769.1952s] Trained quant-etc in 175.1591s for f-1/r-0 (1.70 MB)
[770.1738s] Trained quant-etc in 175.2112s for f-0/r-0 (1.66 MB)
[773.7047s] Trained quant-etc in 175.6393s for f-5/r-0 (1.75 MB)
[777.5444s] Trained rstsf in 117.4372s for f-1/r-0 (1.81 MB)
[779.2311s] Trained quant-etc in 185.8394s for f-4/r-0 (1.67 MB)
[779.6826s] Trained quant-etc in 184.6543s for f-2/r-0 (1.64 MB)
[781.6638s] Trained rstsf in 122.5915s for f-0/r-0 (1.83 MB)
[785.6123s] Trained quant-etc in 143.4104s for f-6/r-0 (1.72 MB)
[785.6130s] Completed training for model quant-etc
[786.0461s] OOF acc for model quant-etc: 0.92
[797.0360s] Trained rstsf in 130.8146s for f-5/r-0 (1.84 MB)
[851.6095s] Trained rstsf in 106.5156s for f-6/r-0 (1.79 MB)
[858.3972s] Trained rstsf in 105.5370s for f-7/r-0 (1.79 MB)
[869.3606s] Trained rstsf in 106.6096s for f-9/r-0 (1.78 MB)
[875.9589s] Trained rstsf in 113.8542s for f-8/r-0 (1.80 MB)
[875.9612s] Completed training for model rstsf
[876.3165s] OOF acc for model rstsf: 0.899
[882.0214s] Completed repetition 0
[882.0219s] Starting stacking model training (single pass)
[892.1924s] Trained probability-ridgecv in 0.0862s for f-0 (0.00 MB)
[893.0553s] Trained probability-ridgecv in 0.0327s for f-5 (0.00 MB)
[893.0971s] Trained probability-ridgecv in 0.0396s for f-6 (0.00 MB)
[893.1129s] Trained probability-ridgecv in 0.0359s for f-4 (0.00 MB)
[893.1631s] Trained probability-ridgecv in 0.0317s for f-1 (0.00 MB)
[893.2018s] Trained probability-ridgecv in 0.0328s for f-9 (0.00 MB)
[894.0390s] Trained probability-ridgecv in 0.0290s for f-7 (0.00 MB)
[897.0046s] Trained probability-ridgecv in 0.0389s for f-3 (0.00 MB)
[899.1675s] Trained probability-ridgecv in 0.0554s for f-8 (0.00 MB)
[900.0651s] Trained probability-ridgecv in 0.0631s for f-2 (0.00 MB)
[909.5749s] OOF acc for model probability-ridgecv: 0.956
[909.5755s] Completed all repetitions and stacking
Executor shutdown complete

LokyStackerV6(n_jobs=16, random_state=492)

In [10]:
y_pred = m.predict(X_test)
acc = accuracy_score(y_test, y_pred)
print(f"Accuracy on {dataset}: {acc}")

[0.0000s] Starting prediction
Starting executor with 16 workers, run_dir=./tscglue/ba1a967a4c724985
[80.0515s] Computed features for prediction
[80.4595s] Feature arrays saved to mmap files
[80.4601s] Starting prediction with 16 workers for 40 first-level models
[88.5427s] Predicted quant-etc in 0.0932s
[88.6181s] Predicted quant-etc in 0.0578s
[88.7049s] Predicted quant-etc in 0.0691s
[88.7830s] Predicted quant-etc in 0.0624s
[88.8449s] Predicted quant-etc in 0.0477s
[89.1192s] Predicted rdst-ridgecv in 0.2479s
[89.3740s] Predicted rdst-ridgecv in 0.2309s
[89.7424s] Predicted rdst-ridgecv in 0.3203s
[89.9576s] Predicted rdst-ridgecv in 0.2163s
[90.2616s] Predicted rdst-ridgecv in 0.2686s
[90.6007s] Predicted rdst-ridgecv in 0.3110s
[90.8752s] Predicted rdst-ridgecv in 0.2468s
[91.2310s] Predicted rdst-ridgecv in 0.3295s
[91.4822s] Predicted rdst-ridgecv in 0.2325s
[91.7882s] Predicted rdst-ridgecv in 0.2750s
[91.9031s] Predicted quant-etc in 0.1751s
[92.1926s] Predicted multirockethydra-ridgecv in 0.3726s
[92.4729s] Predicted quant-etc in 0.1838s
[92.5567s] Predicted multirockethydra-ridgecv in 0.3308s
[92.8976s] Predicted quant-etc in 0.1923s
[92.9872s] Predicted multirockethydra-ridgecv in 0.3959s
[93.4306s] Predicted multirockethydra-ridgecv in 1.4004s
[93.4412s] Predicted multirockethydra-ridgecv in 0.4101s
[93.7790s] Predicted quant-etc in 0.1887s
[93.8986s] Predicted multirockethydra-ridgecv in 1.3020s
[94.0450s] Predicted multirockethydra-ridgecv in 0.5327s
[94.1818s] Predicted multirockethydra-ridgecv in 1.2002s
[94.7128s] Predicted multirockethydra-ridgecv in 1.1827s
[94.8691s] Predicted multirockethydra-ridgecv in 1.0321s
[94.9667s] Predicted quant-etc in 0.1969s
[106.4176s] Predicted rstsf in 19.4119s
[106.7929s] Predicted rstsf in 18.3402s
[107.2992s] Predicted rstsf in 18.6397s
[108.2379s] Predicted rstsf in 18.8721s
[115.8206s] Predicted rstsf in 24.3674s
[116.8540s] Predicted rstsf in 25.4207s
[117.0733s] Predicted rstsf in 26.8066s
[118.3619s] Predicted rstsf in 25.3477s
[118.3869s] Predicted rstsf in 24.0617s
[120.5103s] Predicted rstsf in 26.8600s
[131.0001s] Completed all first-level model predictions
[131.6454s] Starting prediction with 10 workers for 10 stacking models
[140.8604s] Predicted probability-ridgecv in 0.0027s
[141.3968s] Predicted probability-ridgecv in 0.0028s
[141.5995s] Predicted probability-ridgecv in 0.0027s
[141.9238s] Predicted probability-ridgecv in 0.0040s
[141.9633s] Predicted probability-ridgecv in 0.0033s
[142.5896s] Predicted probability-ridgecv in 0.0053s
[142.7901s] Predicted probability-ridgecv in 0.0034s
[143.8145s] Predicted probability-ridgecv in 0.0035s
[144.8284s] Predicted probability-ridgecv in 0.0040s
[145.1171s] Predicted probability-ridgecv in 0.0031s
[156.2342s] Completed all stacking model predictions
Executor shutdown complete
Accuracy on HandOutlines: 0.9486486486486486

In [11]:
m = LokyStackerV5(random_state=492, n_repetitions=1, n_jobs=16)
m.fit(X_train, y_train)

[0.0000s] Starting fitting
[4.0838s] Computed QUANT features in 4.0818s
Starting executor with 16 workers, tmpdir=/tmp/loky_stacker_3q3cggl8
[4.0880s] Starting repetition 0
[13.9102s] Computed MultiRocket features in 9.8222s
[283.0474s] Computed Hydra features in 269.1362s
[396.6775s] Computed RDST features in 113.6263s
[400.5669s] Data saved to mmap files
[400.5678s] Starting training with 16 workers for 40 models
[444.8102s] Trained multirockethydra-ridgecv in 28.8553s for f-1/r-0
[446.1570s] Trained multirockethydra-ridgecv in 34.9631s for f-0/r-0
[447.6943s] Trained multirockethydra-ridgecv in 34.9683s for f-2/r-0
[451.9420s] Trained multirockethydra-ridgecv in 38.3889s for f-5/r-0
[454.1054s] Trained multirockethydra-ridgecv in 41.2305s for f-4/r-0
[454.6687s] Trained multirockethydra-ridgecv in 39.7589s for f-7/r-0
[456.2780s] Trained multirockethydra-ridgecv in 42.7959s for f-6/r-0
[457.9678s] Trained multirockethydra-ridgecv in 41.3337s for f-8/r-0
[458.2378s] Trained multirockethydra-ridgecv in 44.9073s for f-3/r-0
[462.9867s] Trained rdst-ridgecv in 8.2278s for f-1/r-0
[463.4897s] Trained rdst-ridgecv in 9.4897s for f-0/r-0
[464.5332s] Trained rdst-ridgecv in 8.2178s for f-2/r-0
[467.9826s] Trained rdst-ridgecv in 10.2849s for f-3/r-0
[468.3994s] Trained rdst-ridgecv in 9.7266s for f-4/r-0
[474.8863s] Trained rdst-ridgecv in 11.0773s for f-6/r-0
[475.8088s] Trained rdst-ridgecv in 12.6527s for f-5/r-0
[478.4043s] Trained multirockethydra-ridgecv in 52.7294s for f-9/r-0
[478.6574s] Completed training for model multirockethydra-ridgecv
[488.2873s] OOF acc for model multirockethydra-ridgecv: 0.957
[488.2880s] Trained rdst-ridgecv in 14.7770s for f-7/r-0
[488.3770s] Trained rdst-ridgecv in 16.2955s for f-8/r-0
[488.9804s] Trained rdst-ridgecv in 20.5547s for f-9/r-0
[489.2809s] Completed training for model rdst-ridgecv
[495.3038s] OOF acc for model rdst-ridgecv: 0.951
[575.8380s] Trained quant-etc in 149.1916s for f-0/r-0
[576.2841s] Trained quant-etc in 128.0438s for f-8/r-0
[577.1161s] Trained quant-etc in 146.7625s for f-3/r-0
[578.5610s] Trained quant-etc in 149.4780s for f-1/r-0
[578.7146s] Trained quant-etc in 126.9413s for f-9/r-0
[589.8125s] Trained quant-etc in 159.4438s for f-5/r-0
[591.0151s] Trained quant-etc in 160.5791s for f-4/r-0
[603.7793s] Trained quant-etc in 156.8925s for f-7/r-0
[605.1369s] Trained quant-etc in 176.2370s for f-2/r-0
[657.5767s] Trained quant-etc in 212.7349s for f-6/r-0
[657.5987s] Completed training for model quant-etc
[663.6437s] OOF acc for model quant-etc: 0.92
[674.6627s] Trained rstsf in 195.1526s for f-3/r-0
[689.7449s] Trained rstsf in 214.8626s for f-0/r-0
[691.6587s] Trained rstsf in 215.6476s for f-1/r-0
[700.4147s] Trained rstsf in 123.9342s for f-7/r-0
[708.3203s] Trained rstsf in 223.8630s for f-4/r-0
[709.2792s] Trained rstsf in 132.1033s for f-8/r-0
[721.7573s] Trained rstsf in 243.2474s for f-2/r-0
[732.0006s] Trained rstsf in 242.9558s for f-5/r-0
[753.5636s] Trained rstsf in 177.6621s for f-6/r-0
[762.1652s] Trained rstsf in 183.5534s for f-9/r-0
[762.1792s] Completed training for model rstsf
[765.7035s] OOF acc for model rstsf: 0.899
[775.7616s] Completed repetition 0
[775.7620s] Starting stacking model training (single pass)
[808.7277s] Trained probability-ridgecv in 1.5831s for f-0
[809.4148s] Trained probability-ridgecv in 1.5029s for f-1
[810.3836s] Trained probability-ridgecv in 1.6682s for f-2
[810.7819s] Trained probability-ridgecv in 1.3668s for f-3
[812.1519s] Trained probability-ridgecv in 1.7575s for f-4
[815.0762s] Trained probability-ridgecv in 4.2918s for f-5
[816.6270s] Trained probability-ridgecv in 4.4772s for f-6
[818.1912s] Trained probability-ridgecv in 3.1149s for f-7
[818.8355s] Trained probability-ridgecv in 2.2122s for f-8
[819.5451s] Trained probability-ridgecv in 1.3534s for f-9
[834.2583s] OOF acc for model probability-ridgecv: 0.956
[834.2585s] Completed all repetitions and stacking
Executor shutdown complete

LokyStackerV5(n_jobs=16, random_state=492)

In [12]:
y_pred = m.predict(X_test)
acc = accuracy_score(y_test, y_pred)
print(f"Accuracy on {dataset}: {acc}")

[0.0000s] Starting prediction
Starting executor with 16 workers, tmpdir=/tmp/loky_stacker_pred_5rdyed26
[150.0041s] Computed features for prediction
[150.8954s] Data saved to mmap files
[154.0963s] Starting prediction with 16 workers for 40 first-level models
[175.7918s] Predicted quant-etc in 2.0056s
[176.3580s] Predicted quant-etc in 2.7314s
[176.6361s] Predicted quant-etc in 2.0052s
[176.6468s] Predicted quant-etc in 1.8262s
[176.7658s] Predicted quant-etc in 2.0311s
[177.9011s] Predicted quant-etc in 2.6360s
[177.9820s] Predicted quant-etc in 2.1128s
[178.3179s] Predicted quant-etc in 1.5822s
[178.7916s] Predicted quant-etc in 2.2694s
[178.8356s] Predicted quant-etc in 2.0024s
[179.0192s] Predicted rdst-ridgecv in 2.1367s
[181.5736s] Predicted rdst-ridgecv in 3.2975s
[181.6060s] Predicted rdst-ridgecv in 3.5638s
[181.9332s] Predicted rdst-ridgecv in 3.5374s
[182.0416s] Predicted rdst-ridgecv in 3.1726s
[182.0519s] Predicted rdst-ridgecv in 2.9369s
[182.0879s] Predicted rdst-ridgecv in 3.1518s
[183.3942s] Predicted rdst-ridgecv in 1.7152s
[183.4944s] Predicted rdst-ridgecv in 1.4828s
[184.3163s] Predicted rdst-ridgecv in 2.5322s
[186.5371s] Predicted multirockethydra-ridgecv in 4.0694s
[186.5693s] Predicted multirockethydra-ridgecv in 4.1288s
[187.9086s] Predicted multirockethydra-ridgecv in 5.6676s
[187.9639s] Predicted multirockethydra-ridgecv in 4.4162s
[188.1155s] Predicted multirockethydra-ridgecv in 4.4503s
[190.4273s] Predicted multirockethydra-ridgecv in 5.8052s
[191.2824s] Predicted multirockethydra-ridgecv in 4.5897s
[191.6332s] Predicted multirockethydra-ridgecv in 4.8397s
[192.2333s] Predicted multirockethydra-ridgecv in 4.0474s
[192.3659s] Predicted multirockethydra-ridgecv in 4.3126s
[199.4213s] Predicted rstsf in 31.9599s
[200.6349s] Predicted rstsf in 28.4331s
[201.1815s] Predicted rstsf in 29.8000s
[201.4420s] Predicted rstsf in 29.1235s
[201.8655s] Predicted rstsf in 29.5410s
[202.2247s] Predicted rstsf in 30.2388s
[203.4243s] Predicted rstsf in 30.2309s
[203.8839s] Predicted rstsf in 30.3890s
[203.9446s] Predicted rstsf in 30.8832s
[206.0058s] Predicted rstsf in 32.4430s
[216.4653s] Completed all first-level model predictions
[220.2897s] Starting prediction with 10 workers for 10 stacking models
[229.8363s] Predicted probability-ridgecv in 0.1285s
[229.8716s] Predicted probability-ridgecv in 0.0612s
[229.9314s] Predicted probability-ridgecv in 0.0593s
[229.9812s] Predicted probability-ridgecv in 0.0493s
[230.0458s] Predicted probability-ridgecv in 0.0638s
[230.0883s] Predicted probability-ridgecv in 0.0425s
[230.1409s] Predicted probability-ridgecv in 0.0516s
[230.1906s] Predicted probability-ridgecv in 0.0485s
[230.2442s] Predicted probability-ridgecv in 0.0530s
[230.2989s] Predicted probability-ridgecv in 0.0548s
[238.6429s] Completed all stacking model predictions
Executor shutdown complete
Accuracy on HandOutlines: 0.9486486486486486